### ISSUE TITLE
x86_64 rpm build

### ISSUE THREAD

**Issue by 2qU24Tlb** [kunpengcompute/rpmbuild#10]
希望增加x86版本的rpmbuild

**Comment by Yikun** [comment]
@2qU24Tlb 已经有的：
```bash
docker run -ti kunpengcompute/openeuler:20.03.x86_64 bash
```

另外，可以关注[1]，openeuler也在着手增加官方镜像：
[1] https://gitee.com/openeuler/community/issues/I1K1BG

**Comment by Yikun** [comment]
哦。您意思是x86版本的rpmbuild？而不是源镜像？

**Comment by 2qU24Tlb** [comment]
是的，当前的rpmbuild只有aarch64。如果欢迎PR我也可以帮忙。

**Comment by 2qU24Tlb** [comment]
还有问一下，你知道如何启动systemd吗?我最近在做zookeeper的rpm包，发现需要systemd启动。但docker默认是不启动systemd的

**Comment by Yikun** [comment]
@2qU24Tlb 欢迎PR，systemctl试试?

**Comment by 2qU24Tlb** [comment]
added in #11

**Comment by Yikun** [comment]
@2qU24Tlb Looks like the deploy script have some mistake and failed to deploy, I will upload the image manully soon. and fix the deploy script later

**Comment by Yikun** [comment]
Done

版本说明
- rpmbuild: 默认指向rpmbuild.aarch64.
- rpmbuild.aarch64: 基于20.03.aarch64镜像，新增了默认源，安装了一些打包及开发用的必备软件。
- rpmbuild.x86_64: 基于20.03.x86_64镜像，新增了默认源，安装了一些打包及开发用的必备软件。

默认镜像：
- lastest: 最近提交的鲲鹏可用版本，目前指向20.03.aarch64
- 20.03.aarch64: 由官方提供的20.03版本的aarch64镜像构建
- 20.03.x86_64: 由官方提供的20.03版本的x86_64镜像构建
